---
- hosts: all
  become: true
  tasks:
  - name: Install DHCP 
    apt:
      name: isc-dhcp-server
    when: ansible_distribution == "Ubuntu"

  - name: Install DHCP (CentOS)
    dnf:
      name: dhcp-server
      state: latest
    when: ansible_distribution == "CentOS"
   
 
