---
- hosts: all
  become: true
  tasks: 
  - name: Install vsftpd
    apt:
      name: vsftpd
    when: ansible_distribution == "Ubuntu"
  - name: Install vsftpd
    yum:
      name: vsftpd
    when: ansible_distribution == "CentOs"
