---
- hosts: all
  become: true
  tasks: 
  - name: update repository index
    apt:
      update_cache: yes
  - name: Install DHCP
    apt:
      name: DHCP
    when: ansible Distribution == "Ubuntu"
  - name: Install vsftpd
    yum:
      name: vsftpd
    when: ansible Distribution == "CentOs"
