---
#Installing Samba Ubuntu
- hosts: all
  become: true
  tasks:
- name : Install Samba packages
  apt:
    name: "{{ samba_packages }}"
    state: present
  when: ansible_distribution == "Ubuntu"

#Installing Samba Centos
- name Install Samba packages
  dnf: 
    name: "{{ samba_packages }}"
    state: present
  when: ansible_distribution == "Centos"
