---
#Installing Samba Ubuntu
- hosts: all
  become: true
  tasks:
- name : Install Samba packages
  apt:
    name: "{{ samba_packages }}"
    state: present

- name Install Samba packages
  dnf: 
    name: "{{ samba_packages }}"
    state: present
